
version: 2.1

jobs:
  build:
    working_directory: ~/circleci-test
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py

workflows:
  build_now:
    jobs:
      - build
