version: 2.1

jobs:
  build:
    working_directory: ~/circleci-test
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    working_directory: ~/circleci-test
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
