version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
